class_name BalanceIndex
extends RefCounted
## balance.gd 的目录：有哪些数值、每个数值的说明、文件里写的值。
## 自动生成，不要手改。改了 balance.gd 以后运行：
##     godot_console --headless --path game --script res://tools/make_balance_index.gd
## （调试面板「写回 balance.gd」时会自动重新生成；没更新时规则测试会失败。）

const NAMES: Array[String] = [
	"AI_COUNT",
	"P_HAS_STAR",
	"STAR_WEIGHTS",
	"MAX_PLANETS",
	"P_ROCKY",
	"P_HABITABLE_PLANET",
	"HOME_MIN_DISTANCE",
	"START_ENERGY",
	"START_MINERAL",
	"FISSION_ENERGY",
	"ENERGY_PER_SYSTEM",
	"ENERGY_PER_STAR",
	"MINERAL_PER_COLONY",
	"ACTION_BASE",
	"ACTION_MIN",
	"STARSHIP_ENERGY",
	"STARSHIP_MINERAL",
	"TECH_COST",
	"TIER3_ENERGY",
	"TIER_GAP",
	"CONTACT_RANGE",
	"TECH_BURST_CHANCE",
	"VISION_HOME",
	"VISION_COLONY",
	"VISION_SHIP",
	"PROBE_ANGLE",
	"PROBE_LENGTH",
	"IPROBE_ANGLE",
	"IPROBE_LENGTH",
	"MAX_CONE_ANGLE",
	"TELESCOPE_MAX",
	"TELESCOPE_STEP",
	"TELESCOPE_ANGLE_STEP",
	"COST_TELESCOPE",
	"WAKE_SPEED",
	"SIGHTING_KEEP",
	"GRAIN_MOVE",
	"PROBE_MOVE",
	"IPROBE_MOVE",
	"WARSHIP_MOVE",
	"STARSHIP_MOVE",
	"COLONY_MOVE",
	"DEVOURER_MOVE",
	"WARP_MOVE",
	"SLOW_START_SPEED",
	"COST_PROBE",
	"COST_PROBE_LAUNCH",
	"COST_WARSHIP",
	"COST_WARSHIP_GRAVITY",
	"COST_WARSHIP_LAUNCH",
	"COST_TURN",
	"COST_COLONY",
	"COST_STARSHIP",
	"COST_STARSHIP_MOVE",
	"COST_DEVOURER",
	"COST_DEVOURER_LAUNCH",
	"COST_WARP_EXTRA",
	"MAX_WARSHIPS",
	"MAX_COLONY_SHIPS",
	"MAX_STARSHIPS",
	"MAX_DEVOURERS",
	"DEVOURER_MINERAL",
	"COST_MINER",
	"MINER_MINERAL",
	"MAX_MINERS",
	"COST_DYSON",
	"DYSON_ENERGY",
	"COST_BUNKER",
	"COST_BROADCASTER",
	"COST_WARNING",
	"WARNING_RANGE",
	"WARNING_MAX",
	"COST_WARNING_UPGRADE",
	"COST_ANTIMATTER",
	"MAX_ANTIMATTER",
	"ANTIMATTER_RANGE",
	"COST_GRAIN",
	"COST_GRAIN_LAUNCH",
	"GRAIN_RADIUS",
	"WARSHIP_RANGE",
	"BEAM_RANGE",
	"TORPEDO_RANGE",
	"HBOMB_RANGE",
	"COST_BEAM_EXTRA",
	"COST_TORPEDO_EXTRA",
	"COST_HBOMB_EXTRA",
	"BEAM_SHOT",
	"TORPEDO_SHOT",
	"HBOMB_SHOT",
	"TORPEDO_HITS",
	"COST_SOPHON",
	"COST_SOPHON_LAUNCH",
	"SOPHON_MOVE",
	"MAX_SOPHONS",
	"SOPHON_RESEARCH_TURNS",
	"SOPHON_TIER_TURNS",
	"COST_FOIL",
	"COST_LINE_FOIL",
	"FOIL_PREPARE_TURNS",
	"FOIL_SPEED",
	"FOIL_SPREAD",
	"COST_SINGULARITY",
	"SINGULARITY_TURNS",
	"LINE_GRACE_TURNS",
	"COST_REDUCE_BASE",
	"COST_REDUCE_PER_UNIT",
	"REDUCE_TURNS",
	"AI_REDUCE_ALERT",
	"AI_FOIL_HITS",
	"AI_FOIL_ENERGY",
	"COST_BLACK_DOMAIN",
	"BLACK_DOMAIN_PREPARE_TURNS",
	"BLACK_DOMAIN_TURNS",
	"DOMAIN_INCOME",
	"GRAIN_MIN_LIGHT",
	"SHIP_MIN_SPEED",
	"SHIP_STUCK_TURNS",
	"COST_BROADCAST",
	"BROADCAST_EXPOSE_HALF",
	"HIDDEN_COUNT",
	"HIDDEN_HEAR_RANGE",
	"HIDDEN_STRIKE_CHANCE",
	"HIDDEN_PATIENCE",
	"HIDDEN_FOIL_CHANCE",
	"HIDDEN_FOIL_SPEED",
	"DARK_ENERGY_CELLS",
]

const DOCS := {
	"AI_COUNT": "",
	"P_HAS_STAR": "α：一个格子有星系的概率",
	"STAR_WEIGHTS": "β：单星、双星、三星的比例（E7F6 估计 6:3:1 或 7:2:1）",
	"MAX_PLANETS": "单星、双星、三星系统最多几颗行星（0 到这个数随机）",
	"P_ROCKY": "γ：一颗行星是类地行星（不是类木行星）的概率",
	"P_HABITABLE_PLANET": "δ：一颗类地行星宜居的概率",
	"HOME_MIN_DISTANCE": "各文明的母星系彼此至少隔开几格（E7F6 2026-10-07 第三次）",
	"START_ENERGY": "",
	"START_MINERAL": "",
	"FISSION_ENERGY": "裂变能（科技 002）：自己星系里的每颗类地行星每回合多少能量（E7F6 2026-10-06 第二次：+1）",
	"ENERGY_PER_SYSTEM": "每个星系本身的能量：每个星系 ENERGY_PER_SYSTEM，再加每颗恒星 ENERGY_PER_STAR（E7F6 2026-10-06 第二次：只按恒星算，每颗 3E）",
	"ENERGY_PER_STAR": "每个星系本身的能量：每个星系 ENERGY_PER_SYSTEM，再加每颗恒星 ENERGY_PER_STAR（E7F6 2026-10-06 第二次：只按恒星算，每颗 3E）",
	"MINERAL_PER_COLONY": "每个星系本身每回合的矿石",
	"ACTION_BASE": "行动点 = ACTION_BASE − 母星系的恒星数，每多一个殖民地 +1（E2），最少 ACTION_MIN",
	"ACTION_MIN": "行动点 = ACTION_BASE − 母星系的恒星数，每多一个殖民地 +1（E2），最少 ACTION_MIN",
	"STARSHIP_ENERGY": "星系全丢了、只剩星舰时每回合的收入",
	"STARSHIP_MINERAL": "星系全丢了、只剩星舰时每回合的收入",
	"TECH_COST": "每项科技的价格：[能量, 矿石]。越高级、收益越高越贵（T2）。0 级开局就有，不用买。",
	"TIER3_ENERGY": "III 级的门槛：每回合的能量收入达到多少（E8：35E）",
	"TIER_GAP": "一级开放以后，至少过这么多回合才开下一级（E8：先发展一段时间）",
	"CONTACT_RANGE": "II 级的「接触」：自己的舰船和别人的舰船相距这么近（E8）",
	"TECH_BURST_CHANCE": "AI 每回合不花资源直接得到一项能升的科技的机会（技术爆炸，D6）",
	"VISION_HOME": "",
	"VISION_COLONY": "殖民星系和星舰",
	"VISION_SHIP": "战舰、殖民船、吞噬者",
	"PROBE_ANGLE": "探测器圆锥的张角（度）",
	"PROBE_LENGTH": "",
	"IPROBE_ANGLE": "星际探测器",
	"IPROBE_LENGTH": "",
	"MAX_CONE_ANGLE": "",
	"TELESCOPE_MAX": "射电望远镜（科技 003）：每次升级所有视野和圆锥长度 +TELESCOPE_STEP 格，张角 +15°，最多 4 次（T18）",
	"TELESCOPE_STEP": "射电望远镜（科技 003）：每次升级所有视野和圆锥长度 +TELESCOPE_STEP 格，张角 +15°，最多 4 次（T18）",
	"TELESCOPE_ANGLE_STEP": "射电望远镜（科技 003）：每次升级所有视野和圆锥长度 +TELESCOPE_STEP 格，张角 +15°，最多 4 次（T18）",
	"COST_TELESCOPE": "能量，每次升级",
	"WAKE_SPEED": "近光速舰船（每回合超过这么多格）留下航迹",
	"SIGHTING_KEEP": "看到的飞船过了这么多回合就不再画",
	"GRAIN_MOVE": "",
	"PROBE_MOVE": "",
	"IPROBE_MOVE": "",
	"WARSHIP_MOVE": "",
	"STARSHIP_MOVE": "",
	"COLONY_MOVE": "",
	"DEVOURER_MOVE": "",
	"WARP_MOVE": "",
	"SLOW_START_SPEED": "探测器选「先慢速飞出视野」时，在自己星系的视野里最快多少（G13.4）",
	"COST_PROBE": "单位造好后停在星系里，下一步「派出」时才出发（建造和调度各花 1 行动点）。",
	"COST_PROBE_LAUNCH": "能量",
	"COST_WARSHIP": "单位造好后停在星系里，下一步「派出」时才出发（建造和调度各花 1 行动点）。",
	"COST_WARSHIP_GRAVITY": "带引力波广播器的战舰多花的能量（科技 203）",
	"COST_WARSHIP_LAUNCH": "能量",
	"COST_TURN": "战舰、吞噬者转向，能量（G8）",
	"COST_COLONY": "单位造好后停在星系里，下一步「派出」时才出发（建造和调度各花 1 行动点）。",
	"COST_STARSHIP": "单位造好后停在星系里，下一步「派出」时才出发（建造和调度各花 1 行动点）。",
	"COST_STARSHIP_MOVE": "单位造好后停在星系里，下一步「派出」时才出发（建造和调度各花 1 行动点）。",
	"COST_DEVOURER": "单位造好后停在星系里，下一步「派出」时才出发（建造和调度各花 1 行动点）。",
	"COST_DEVOURER_LAUNCH": "单位造好后停在星系里，下一步「派出」时才出发（建造和调度各花 1 行动点）。",
	"COST_WARP_EXTRA": "装了曲率引擎的舰船多花的能量（科技 205）",
	"MAX_WARSHIPS": "单位造好后停在星系里，下一步「派出」时才出发（建造和调度各花 1 行动点）。",
	"MAX_COLONY_SHIPS": "单位造好后停在星系里，下一步「派出」时才出发（建造和调度各花 1 行动点）。",
	"MAX_STARSHIPS": "单位造好后停在星系里，下一步「派出」时才出发（建造和调度各花 1 行动点）。",
	"MAX_DEVOURERS": "暂定（游戏设计 §12）",
	"DEVOURER_MINERAL": "吃掉一颗类地行星得到的矿石（暂定）",
	"COST_MINER": "采矿船：建在自己的星系上，下一回合建好，每艘每回合多产矿石",
	"MINER_MINERAL": "采矿船：建在自己的星系上，下一回合建好，每艘每回合多产矿石",
	"MAX_MINERS": "每个星系最多几艘（E7F6 2026-10-07 第三次：1 → 5）",
	"COST_DYSON": "戴森球：总数不超过自己所有星系的恒星总数，下一回合建好",
	"DYSON_ENERGY": "戴森球：总数不超过自己所有星系的恒星总数，下一回合建好",
	"COST_BUNKER": "掩体：只能建在有类木行星的自己的星系上，每个星系一个，建好后一直存在",
	"COST_BROADCASTER": "恒星广播器：建在某个星系上，从那里广播",
	"COST_WARNING": "预警系统：整个文明一个；范围从母星系和殖民星系算起，可以升级",
	"WARNING_RANGE": "预警系统：整个文明一个；范围从母星系和殖民星系算起，可以升级",
	"WARNING_MAX": "预警系统：整个文明一个；范围从母星系和殖民星系算起，可以升级",
	"COST_WARNING_UPGRADE": "能量，每次 +1 格",
	"COST_ANTIMATTER": "反物质：要花大量能量，最多存 1 份；敌方战舰在自己星系这么近时可以下令用掉",
	"MAX_ANTIMATTER": "反物质：要花大量能量，最多存 1 份；敌方战舰在自己星系这么近时可以下令用掉",
	"ANTIMATTER_RANGE": "反物质：要花大量能量，最多存 1 份；敌方战舰在自己星系这么近时可以下令用掉",
	"COST_GRAIN": "光粒：「造光粒」花矿石，存在那个星系里，每个星系最多 1 颗；「发射光粒」花能量（G2）",
	"COST_GRAIN_LAUNCH": "光粒：「造光粒」花矿石，存在那个星系里，每个星系最多 1 颗；「发射光粒」花能量（G2）",
	"GRAIN_RADIUS": "打击范围：半径 0.5 的圆柱（会再加半个格子）",
	"WARSHIP_RANGE": "「附近」：周围 1.0 格（T19）",
	"BEAM_RANGE": "高能粒子束：直接毁掉",
	"TORPEDO_RANGE": "星际鱼雷：打中 TORPEDO_HITS 次才毁掉",
	"HBOMB_RANGE": "次声波氢弹：杀死船员，收回对方造船花的资源",
	"COST_BEAM_EXTRA": "升级后，之后造的战舰都带上，每带一种多花 COST_xxx_EXTRA [能量, 矿石]；敌方战舰进了射程就自动开火，每次花 xxx_SHOT [能量, 矿石]",
	"COST_TORPEDO_EXTRA": "升级后，之后造的战舰都带上，每带一种多花 COST_xxx_EXTRA [能量, 矿石]；敌方战舰进了射程就自动开火，每次花 xxx_SHOT [能量, 矿石]",
	"COST_HBOMB_EXTRA": "升级后，之后造的战舰都带上，每带一种多花 COST_xxx_EXTRA [能量, 矿石]；敌方战舰进了射程就自动开火，每次花 xxx_SHOT [能量, 矿石]",
	"BEAM_SHOT": "升级后，之后造的战舰都带上，每带一种多花 COST_xxx_EXTRA [能量, 矿石]；敌方战舰进了射程就自动开火，每次花 xxx_SHOT [能量, 矿石]",
	"TORPEDO_SHOT": "升级后，之后造的战舰都带上，每带一种多花 COST_xxx_EXTRA [能量, 矿石]；敌方战舰进了射程就自动开火，每次花 xxx_SHOT [能量, 矿石]",
	"HBOMB_SHOT": "升级后，之后造的战舰都带上，每带一种多花 COST_xxx_EXTRA [能量, 矿石]；敌方战舰进了射程就自动开火，每次花 xxx_SHOT [能量, 矿石]",
	"TORPEDO_HITS": "星际鱼雷打中几次才毁掉一艘战舰",
	"COST_SOPHON": "造一个智子 [能量, 矿石]",
	"COST_SOPHON_LAUNCH": "能量",
	"SOPHON_MOVE": "一出发就是 0.99",
	"MAX_SOPHONS": "同时最多有几个智子",
	"SOPHON_RESEARCH_TURNS": "到了别人的母星系以后，对方这么多回合不能升级科技、这么多回合达到的科技等级条件不算",
	"SOPHON_TIER_TURNS": "到了别人的母星系以后，对方这么多回合不能升级科技、这么多回合达到的科技等级条件不算",
	"COST_FOIL": "",
	"COST_LINE_FOIL": "",
	"FOIL_PREPARE_TURNS": "",
	"FOIL_SPEED": "展开前每回合飞多远（B7）",
	"FOIL_SPREAD": "展开后每回合向外扩散多远（T17）",
	"COST_SINGULARITY": "奇异点：全图压成直线后，准备这么多回合，完成的文明降到零维，赢得对局",
	"SINGULARITY_TURNS": "奇异点：全图压成直线后，准备这么多回合，完成的文明降到零维，赢得对局",
	"LINE_GRACE_TURNS": "全图压成直线后，这么多回合内没人完成奇异点，就平局",
	"COST_REDUCE_BASE": "自身降维：花几个回合进入下一维，期间不能建造。全部单位一起携带、按个数收费。",
	"COST_REDUCE_PER_UNIT": "自身降维：花几个回合进入下一维，期间不能建造。全部单位一起携带、按个数收费。",
	"REDUCE_TURNS": "自身降维：花几个回合进入下一维，期间不能建造。全部单位一起携带、按个数收费。",
	"AI_REDUCE_ALERT": "AI 发现二向箔再过这么多回合以内就会压到自己的星系时，开始降维",
	"AI_FOIL_HITS": "仅剩一个据点时，至少被打多少次才考虑末日武器",
	"AI_FOIL_ENERGY": "AI 能量攒到这么多、又有已知目标时，先降维再发射二向箔",
	"COST_BLACK_DOMAIN": "",
	"BLACK_DOMAIN_PREPARE_TURNS": "",
	"BLACK_DOMAIN_TURNS": "中心的光速保持 0 几回合，然后慢慢恢复（G14）",
	"DOMAIN_INCOME": "被困在黑域里的星系，产出变成原来的多少（向上取整，G14）",
	"GRAIN_MIN_LIGHT": "每格的光速（G14）：光速低于 GRAIN_MIN_LIGHT 的地方光粒没有杀伤力，也算「在黑域里」；舰船实际速度低于 SHIP_MIN_SPEED 就停在原地，这样过 SHIP_STUCK_TURNS 回合就消失。光速低于 SHIP_MIN_SPEED 的格子，光和情报也过不去。",
	"SHIP_MIN_SPEED": "每格的光速（G14）：光速低于 GRAIN_MIN_LIGHT 的地方光粒没有杀伤力，也算「在黑域里」；舰船实际速度低于 SHIP_MIN_SPEED 就停在原地，这样过 SHIP_STUCK_TURNS 回合就消失。光速低于 SHIP_MIN_SPEED 的格子，光和情报也过不去。",
	"SHIP_STUCK_TURNS": "每格的光速（G14）：光速低于 GRAIN_MIN_LIGHT 的地方光粒没有杀伤力，也算「在黑域里」；舰船实际速度低于 SHIP_MIN_SPEED 就停在原地，这样过 SHIP_STUCK_TURNS 回合就消失。光速低于 SHIP_MIN_SPEED 的格子，光和情报也过不去。",
	"COST_BROADCAST": "",
	"BROADCAST_EXPOSE_HALF": "广播者离被广播的坐标这么远时，有一半机会暴露自己（B6）",
	"HIDDEN_COUNT": "星图外的隐藏文明有几个",
	"HIDDEN_HEAR_RANGE": "隐藏文明离被广播的坐标多远以内会出手；越近越可能出手",
	"HIDDEN_STRIKE_CHANCE": "听到以后每回合出手的机会（紧挨着时），距离越远按比例越小",
	"HIDDEN_PATIENCE": "听到以后最多等这么多回合，过了就不管了",
	"HIDDEN_FOIL_CHANCE": "出手时用二向箔（否则用光粒）的机会",
	"HIDDEN_FOIL_SPEED": "隐藏文明的二向箔和别人的一样快（游戏设计 §8）",
	"DARK_ENERGY_CELLS": "视野里每这么多格 +1 能量",
}

const DEFAULTS := {
	"AI_COUNT": 4,
	"P_HAS_STAR": 0.55,
	"STAR_WEIGHTS": [6, 3, 1],
	"MAX_PLANETS": [8, 5, 3],
	"P_ROCKY": 0.5,
	"P_HABITABLE_PLANET": 0.1,
	"HOME_MIN_DISTANCE": 5.0,
	"START_ENERGY": 20,
	"START_MINERAL": 20,
	"FISSION_ENERGY": 1,
	"ENERGY_PER_SYSTEM": 0,
	"ENERGY_PER_STAR": 3,
	"MINERAL_PER_COLONY": 2,
	"ACTION_BASE": 6,
	"ACTION_MIN": 2,
	"STARSHIP_ENERGY": 2,
	"STARSHIP_MINERAL": 1,
	"TECH_COST": {
		"dyson": [10, 0], "interstellar_probe": [8, 6], "warship": [10, 8], "bunker": [8, 4],
		"devourer": [16, 12], "grain": [20, 0], "gravity": [12, 4], "antimatter": [16, 0], "warp": [24, 8],
		"starship": [16, 12], "beam": [12, 0], "torpedo": [4, 10], "hbomb": [16, 12], "sophon": [24, 0],
		"dark_energy": [40, 0], "dimension": [50, 0], "domain": [40, 0],
	},
	"TIER3_ENERGY": 35,
	"TIER_GAP": 8,
	"CONTACT_RANGE": 1.0,
	"TECH_BURST_CHANCE": 0.02,
	"VISION_HOME": 2.0,
	"VISION_COLONY": 1.5,
	"VISION_SHIP": 1.0,
	"PROBE_ANGLE": 15.0,
	"PROBE_LENGTH": 1.0,
	"IPROBE_ANGLE": 30.0,
	"IPROBE_LENGTH": 1.5,
	"MAX_CONE_ANGLE": 60.0,
	"TELESCOPE_MAX": 4,
	"TELESCOPE_STEP": 0.5,
	"TELESCOPE_ANGLE_STEP": 15.0,
	"COST_TELESCOPE": 12,
	"WAKE_SPEED": 0.9,
	"SIGHTING_KEEP": 12,
	"GRAIN_MOVE": [1.0, 0.5],
	"PROBE_MOVE": [0.99, 0.02],
	"IPROBE_MOVE": [0.99, 0.1],
	"WARSHIP_MOVE": [0.8, 0.1],
	"STARSHIP_MOVE": [0.6, 0.1],
	"COLONY_MOVE": [0.2, 0.05],
	"DEVOURER_MOVE": [0.15, 0.03],
	"WARP_MOVE": [1.0, 1.0],
	"SLOW_START_SPEED": 0.15,
	"COST_PROBE": [0, 3],
	"COST_PROBE_LAUNCH": 1,
	"COST_WARSHIP": [8, 10],
	"COST_WARSHIP_GRAVITY": 4,
	"COST_WARSHIP_LAUNCH": 2,
	"COST_TURN": 2,
	"COST_COLONY": [10, 10],
	"COST_STARSHIP": [16, 16],
	"COST_STARSHIP_MOVE": 2,
	"COST_DEVOURER": [10, 20],
	"COST_DEVOURER_LAUNCH": 2,
	"COST_WARP_EXTRA": 4,
	"MAX_WARSHIPS": 3,
	"MAX_COLONY_SHIPS": 2,
	"MAX_STARSHIPS": 1,
	"MAX_DEVOURERS": 1,
	"DEVOURER_MINERAL": 20,
	"COST_MINER": [0, 4],
	"MINER_MINERAL": 2,
	"MAX_MINERS": 5,
	"COST_DYSON": [0, 16],
	"DYSON_ENERGY": 6,
	"COST_BUNKER": [8, 8],
	"COST_BROADCASTER": [6, 0],
	"COST_WARNING": [10, 0],
	"WARNING_RANGE": 2.0,
	"WARNING_MAX": 4,
	"COST_WARNING_UPGRADE": 8,
	"COST_ANTIMATTER": [16, 0],
	"MAX_ANTIMATTER": 1,
	"ANTIMATTER_RANGE": 1.0,
	"COST_GRAIN": [0, 8],
	"COST_GRAIN_LAUNCH": 18,
	"GRAIN_RADIUS": 0.5,
	"WARSHIP_RANGE": 1.0,
	"BEAM_RANGE": 1.5,
	"TORPEDO_RANGE": 2.0,
	"HBOMB_RANGE": 1.0,
	"COST_BEAM_EXTRA": [4, 0],
	"COST_TORPEDO_EXTRA": [0, 4],
	"COST_HBOMB_EXTRA": [4, 4],
	"BEAM_SHOT": [3, 0],
	"TORPEDO_SHOT": [0, 3],
	"HBOMB_SHOT": [3, 3],
	"TORPEDO_HITS": 2,
	"COST_SOPHON": [40, 1],
	"COST_SOPHON_LAUNCH": 3,
	"SOPHON_MOVE": [0.99, 0.99],
	"MAX_SOPHONS": 2,
	"SOPHON_RESEARCH_TURNS": 5,
	"SOPHON_TIER_TURNS": 15,
	"COST_FOIL": 30,
	"COST_LINE_FOIL": 30,
	"FOIL_PREPARE_TURNS": 2,
	"FOIL_SPEED": 0.2,
	"FOIL_SPREAD": 0.9,
	"COST_SINGULARITY": 30,
	"SINGULARITY_TURNS": 3,
	"LINE_GRACE_TURNS": 15,
	"COST_REDUCE_BASE": 10,
	"COST_REDUCE_PER_UNIT": 5,
	"REDUCE_TURNS": 3,
	"AI_REDUCE_ALERT": 4,
	"AI_FOIL_HITS": 2,
	"AI_FOIL_ENERGY": 60,
	"COST_BLACK_DOMAIN": 28,
	"BLACK_DOMAIN_PREPARE_TURNS": 2,
	"BLACK_DOMAIN_TURNS": 10,
	"DOMAIN_INCOME": 0.1,
	"GRAIN_MIN_LIGHT": 0.95,
	"SHIP_MIN_SPEED": 0.01,
	"SHIP_STUCK_TURNS": 5,
	"COST_BROADCAST": 6,
	"BROADCAST_EXPOSE_HALF": 4.0,
	"HIDDEN_COUNT": 15,
	"HIDDEN_HEAR_RANGE": 10.0,
	"HIDDEN_STRIKE_CHANCE": 0.15,
	"HIDDEN_PATIENCE": 10,
	"HIDDEN_FOIL_CHANCE": 0.1,
	"HIDDEN_FOIL_SPEED": 0.2,
	"DARK_ENERGY_CELLS": 10,
}
